FROM almalinux:9
RUN dnf install nginx -y 
CMD ["nginx", "-g", "daemon off;"]
LABEl course = "RoboShop DevOps" \
      author="Neelima" \
      email="neel@gmail.com"




#label - to add metadata to the image,
# it is in key value pair format, 
#it is used for documentation purpose, it does not have any effect on the image, it is used to provide information about the image, it can be used to filter images, it can be used to search images, it can be used to organize images, it can be used to manage images, it can be used to automate tasks, it can be used to integrate with other tools, it can be used to track images, it can be used to monitor images, it can be used to secure images, it can be used to optimize images, it can be used to troubleshoot images, it can be used to debug images, it can be used to test images, it can be used to deploy images, it can be used to scale images, it can be used to update images, it can be used to maintain images, it can be used to retire images.
#Alma linux is same as redhat,can view logs  

#RUN is used at the time of building the image

#CMD is used at the time of running the container
#only one CMD is present in a dockerfile, if multiple CMD is present only the last one will be considered
