FROM almalinux:9
ENTRYPOINT ["ping"]
CMD ["google.com"]
#CMD ["ping" , "google.com"]

#ENTRYPOINT ["ping" , "google.com"]

#we can use both CMD and entrypoint for best results



#docker run entry:1.4.0 ping facebook.com
#ping: ping: Name or service not known


#We cant override the entrypoint, if we try to do so it will go and append.



#Entrypoint is used to provide the command executed by the container when it is started

#CMD is used to provide the default command executed by the container when it is started, it can be overridden by providing a command at the time of running the container

#CMD - we can ovveride the command at run time
