FROM almalinux:9
CMD ["ping" , "google.com"]






#Entrypoint is used to provide the command executed by the container when it is started

#CMD is used to provide the default command executed by the container when it is started, it can be overridden by providing a command at the time of running the container