FROM nginx:1.29.7
RUN rm -f /usr/share/nginx/html/index.html
COPY index.html /usr/share/nginx/html/
RUN chmod 644 /usr/share/nginx/html/index.html

#COPY AND ADD

#ADD
#it can fetch content from url/internet and can untar the content in image

#COPY - copied the files from local to image, it does not have any other functionality